version: "3.8"

services:
  mysql:
    image: mysql:latest
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: hfdy_pan
      MYSQL_ROOT_PASSWORD: 123456
      TZ: Asia/Shanghai
    volumes:
      - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql

  redis:
    image: redislabs/rebloom:latest
    ports:
      - "6379:6379"
    environment:
      TZ: Asia/Shanghai

  minio:
    image: minio/minio:latest
    ports:
      - "9000:9000" # 数据操作端口
      - "9001:9001" # 控制台端口
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123
      TZ: Asia/Shanghai
    command: server /data --console-address ":9000" --address ":9001" # webui


